console.log("fhirDemo.js :-)")

// starting a fhir from http://agrueneberg.github.io/FHIR-JS/fhir.min.js
var FHIR = require("fhir");
var fhir = new FHIR({
    url: " https://fhir.herokuapp.com",
});

// FHIR-Demo

fhirDemo=function(){
    // ini actions
    fhirDemo.UI();
}


fhirDemo.UI=function(){
    var div0=document.getElementById('divFHIRdemo');
    if(!div0){alert('this demo expects to a hosting <div> with .id="divFHIRdemo" ')}
    else{
        // input div
        var div = document.createElement('div');
        div0.appendChild(div);
        div.innerHTML='<p style="color:navy">Paste HL& text message or load it from <i style="color:red">.hl7</i> file:</p>';
        div.innerHTML+='<textarea style="width:100%;height:200" id="divFHIRdemo_textArea">';
        var upload =function(x){
            var ta = document.getElementById('divFHIRdemo_textArea');
            ta.value=x.result;
            4
        }
        var divUpload = document.createElement('div');div.appendChild(divUpload);
        jmat.inputFileTxt(upload,divUpload,'','accept=".hl7"');
        
        4
        
    }
    //jmat.inputFileTxt(this.parseGPScvsHTML,div1,'<span style="color:blue">Upload .cvs file generated by gps.wustl.edu</span>','accept=".hl7"');
    
}